#!/bin/bash
# This hook is run after every virtualenv is activated.

export FLEX_HOME=/Developer/SDKs/flex_sdk_4/

VIRTUAL_ENV_NAME=`basename $VIRTUAL_ENV`
VIRTUAL_ENV_CHECKOUT_DIRECTORY=`echo $VIRTUAL_ENV | sed 's/.virtualenvs/Sites/'`
cd $VIRTUAL_ENV_CHECKOUT_DIRECTORY

function toggle() {
	if [[ `pwd` =~ "${VIRTUAL_ENV_CHECKOUT_DIRECTORY}/python-development" ]]; then
		cd "${VIRTUAL_ENV_CHECKOUT_DIRECTORY}/flash-development"
	else
		cd "${VIRTUAL_ENV_CHECKOUT_DIRECTORY}/python-development"
	fi
}

if [ -d "python-development/${VIRTUAL_ENV_NAME}" ]; then
	cd "python-development/${VIRTUAL_ENV_NAME}"
fi

if [ -d $VIRTUAL_ENV_NAME ]; then
	cd $VIRTUAL_ENV_NAME
fi


if [ -d "$VIRTUAL_ENV_CHECKOUT_DIRECTORY/bin" ]; then
    export PATH="$PATH:$VIRTUAL_ENV_CHECKOUT_DIRECTORY/bin"
    
    function buildout {
        local OLDPATH
        OLDPATH=`pwd`
        cd "$VIRTUAL_ENV_CHECKOUT_DIRECTORY"
        ./bin/buildout
        cd "$OLDPATH"
    }
    
    function cdsrc {
        cd "$VIRTUAL_ENV_CHECKOUT_DIRECTORY/src/$1"
    }
    
    alias cdco="cd $VIRTUAL_ENV_CHECKOUT_DIRECTORY"
    alias cdomelette="cd $VIRTUAL_ENV_CHECKOUT_DIRECTORY/omelette"
    alias cds=cdsrc
    
    function ntest {
        local OLDPATH
        OLDPATH=`pwd`
        cd "$VIRTUAL_ENV_CHECKOUT_DIRECTORY"
        echo "./bin/test -w $OLDPATH"
        ./bin/test -w $OLDPATH -v -s --with-doctest --doctest-tests $*
        cd "$OLDPATH"    
    }
    
    function _list_virtual_env_source_dir() {
        local matches cur
        matches=`ls "$VIRTUAL_ENV_CHECKOUT_DIRECTORY/src"`
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        COMPREPLY=( $(compgen -W "${matches}" -- ${cur}) )
        return 0
    }
    
    complete -F _list_virtual_env_source_dir cdsrc
    complete -F _list_virtual_env_source_dir cds
fi